// Code generated by mockery v1.0.0
package mocks

import faker "github.com/nebtex/omniql/tools/faker"
import hybrids "github.com/nebtex/hybrids/golang/hybrids"
import mock "github.com/stretchr/testify/mock"
import oreflection "github.com/nebtex/omniql/commons/golang/oreflection"

// FieldGenerator is an autogenerated mock type for the FieldGenerator type
type FieldGenerator struct {
	mock.Mock
}

// Boolean provides a mock function with given fields: path, field
func (_m *FieldGenerator) Boolean(path string, field oreflection.OType) (bool, error) {
	ret := _m.Called(path, field)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) bool); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Byte provides a mock function with given fields: path, field
func (_m *FieldGenerator) Byte(path string, field oreflection.OType) ([]byte, error) {
	ret := _m.Called(path, field)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) []byte); ok {
		r0 = rf(path, field)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Enumeration provides a mock function with given fields:
func (_m *FieldGenerator) Enumeration() faker.EnumerationGenerator {
	ret := _m.Called()

	var r0 faker.EnumerationGenerator
	if rf, ok := ret.Get(0).(func() faker.EnumerationGenerator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(faker.EnumerationGenerator)
		}
	}

	return r0
}

// Float32 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Float32(path string, field oreflection.OType) (float32, error) {
	ret := _m.Called(path, field)

	var r0 float32
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) float32); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(float32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Float64 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Float64(path string, field oreflection.OType) (float64, error) {
	ret := _m.Called(path, field)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) float64); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Int16 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Int16(path string, field oreflection.OType) (int16, error) {
	ret := _m.Called(path, field)

	var r0 int16
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) int16); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(int16)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Int32 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Int32(path string, field oreflection.OType) (int32, error) {
	ret := _m.Called(path, field)

	var r0 int32
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) int32); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Int64 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Int64(path string, field oreflection.OType) (int64, error) {
	ret := _m.Called(path, field)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) int64); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Int8 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Int8(path string, field oreflection.OType) (int8, error) {
	ret := _m.Called(path, field)

	var r0 int8
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) int8); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(int8)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceID provides a mock function with given fields: path, field, resourceIdType
func (_m *FieldGenerator) ResourceID(path string, field oreflection.OType, resourceIdType hybrids.ResourceIDType) ([]byte, error) {
	ret := _m.Called(path, field, resourceIdType)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, oreflection.OType, hybrids.ResourceIDType) []byte); ok {
		r0 = rf(path, field, resourceIdType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType, hybrids.ResourceIDType) error); ok {
		r1 = rf(path, field, resourceIdType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShouldBeNil provides a mock function with given fields: path, ot
func (_m *FieldGenerator) ShouldBeNil(path string, ot oreflection.OType) (bool, error) {
	ret := _m.Called(path, ot)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) bool); ok {
		r0 = rf(path, ot)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, ot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// String provides a mock function with given fields: path, field
func (_m *FieldGenerator) String(path string, field oreflection.OType) (string, error) {
	ret := _m.Called(path, field)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) string); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uint16 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Uint16(path string, field oreflection.OType) (uint16, error) {
	ret := _m.Called(path, field)

	var r0 uint16
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) uint16); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uint32 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Uint32(path string, field oreflection.OType) (uint32, error) {
	ret := _m.Called(path, field)

	var r0 uint32
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) uint32); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uint64 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Uint64(path string, field oreflection.OType) (uint64, error) {
	ret := _m.Called(path, field)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) uint64); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uint8 provides a mock function with given fields: path, field
func (_m *FieldGenerator) Uint8(path string, field oreflection.OType) (uint8, error) {
	ret := _m.Called(path, field)

	var r0 uint8
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) uint8); ok {
		r0 = rf(path, field)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VectorLen provides a mock function with given fields: path, ot
func (_m *FieldGenerator) VectorLen(path string, ot oreflection.OType) (int, error) {
	ret := _m.Called(path, ot)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, oreflection.OType) int); ok {
		r0 = rf(path, ot)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, oreflection.OType) error); ok {
		r1 = rf(path, ot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
