// Code generated by mockery v1.0.0
package mocks

import hybrids "github.com/nebtex/hybrids/golang/hybrids"
import mock "github.com/stretchr/testify/mock"
import oreflection "github.com/nebtex/omniql/commons/golang/oreflection"

// Items is an autogenerated mock type for the Items type
type Items struct {
	mock.Mock
}

// HybridType provides a mock function with given fields:
func (_m *Items) HybridType() hybrids.Types {
	ret := _m.Called()

	var r0 hybrids.Types
	if rf, ok := ret.Get(0).(func() hybrids.Types); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(hybrids.Types)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Items) Type() oreflection.OType {
	ret := _m.Called()

	var r0 oreflection.OType
	if rf, ok := ret.Get(0).(func() oreflection.OType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oreflection.OType)
		}
	}

	return r0
}
