// Code generated by mockery v1.0.0
package mocks

import hybrids "github.com/nebtex/hybrids/golang/hybrids"
import mock "github.com/stretchr/testify/mock"
import oreflection "github.com/nebtex/omniql/commons/golang/oreflection"

// LookupTableOnUnion is an autogenerated mock type for the LookupTableOnUnion type
type LookupTableOnUnion struct {
	mock.Mock
}

// ByPositionToCamelCase provides a mock function with given fields: input
func (_m *LookupTableOnUnion) ByPositionToCamelCase(input hybrids.UnionKind) (string, oreflection.OType, bool) {
	ret := _m.Called(input)

	var r0 string
	if rf, ok := ret.Get(0).(func(hybrids.UnionKind) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 oreflection.OType
	if rf, ok := ret.Get(1).(func(hybrids.UnionKind) oreflection.OType); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(oreflection.OType)
		}
	}

	var r2 bool
	if rf, ok := ret.Get(2).(func(hybrids.UnionKind) bool); ok {
		r2 = rf(input)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// ByPositionToSnakeCase provides a mock function with given fields: input
func (_m *LookupTableOnUnion) ByPositionToSnakeCase(input hybrids.UnionKind) (string, oreflection.OType, bool) {
	ret := _m.Called(input)

	var r0 string
	if rf, ok := ret.Get(0).(func(hybrids.UnionKind) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 oreflection.OType
	if rf, ok := ret.Get(1).(func(hybrids.UnionKind) oreflection.OType); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(oreflection.OType)
		}
	}

	var r2 bool
	if rf, ok := ret.Get(2).(func(hybrids.UnionKind) bool); ok {
		r2 = rf(input)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// ByString provides a mock function with given fields: input
func (_m *LookupTableOnUnion) ByString(input string) (hybrids.UnionKind, oreflection.OType, bool) {
	ret := _m.Called(input)

	var r0 hybrids.UnionKind
	if rf, ok := ret.Get(0).(func(string) hybrids.UnionKind); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(hybrids.UnionKind)
	}

	var r1 oreflection.OType
	if rf, ok := ret.Get(1).(func(string) oreflection.OType); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(oreflection.OType)
		}
	}

	var r2 bool
	if rf, ok := ret.Get(2).(func(string) bool); ok {
		r2 = rf(input)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}
