// Code generated by mockery v1.0.0
package mocks

import corev1 "github.com/nebtex/omniql/pkg/next/corev1"
import mock "github.com/stretchr/testify/mock"
import oreflection "github.com/nebtex/omniql/commons/golang/oreflection"

// Union is an autogenerated mock type for the Union type
type Union struct {
	mock.Mock
}

// LookupTable provides a mock function with given fields:
func (_m *Union) LookupTable() oreflection.LookupTableOnUnion {
	ret := _m.Called()

	var r0 oreflection.LookupTableOnUnion
	if rf, ok := ret.Get(0).(func() oreflection.LookupTableOnUnion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oreflection.LookupTableOnUnion)
		}
	}

	return r0
}

// Schema provides a mock function with given fields:
func (_m *Union) Schema() corev1.UnionReader {
	ret := _m.Called()

	var r0 corev1.UnionReader
	if rf, ok := ret.Get(0).(func() corev1.UnionReader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1.UnionReader)
		}
	}

	return r0
}
