// automatically generated by the FlatBuffers compiler, do not modify

package 

const (
	ColorRed = 1
	ColorGreen = 2
	ColorBlue = 3
)

var EnumNamesColor = map[int]string{
	ColorRed:"Red",
	ColorGreen:"Green",
	ColorBlue:"Blue",
}

