// automatically generated by the FlatBuffers compiler, do not modify

package omnimap

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Load struct {
	_tab flatbuffers.Table
}

func GetRootAsLoad(buf []byte, offset flatbuffers.UOffsetT) *Load {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Load{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Load) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Load) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Load) Casa() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LoadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LoadAddCasa(builder *flatbuffers.Builder, casa flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(casa), 0)
}
func LoadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
