// automatically generated by the FlatBuffers compiler, do not modify

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type mil struct {
	_tab flatbuffers.Table
}

func GetRootAsmil(buf []byte, offset flatbuffers.UOffsetT) *mil {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &mil{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *mil) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *mil) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *mil) Ju() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *mil) MutateJu(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func milStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func milAddJu(builder *flatbuffers.Builder, ju float32) {
	builder.PrependFloat32Slot(0, ju, 0.0)
}
func milEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
