// automatically generated by the FlatBuffers compiler, do not modify

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResourceEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsResourceEntry(buf []byte, offset flatbuffers.UOffsetT) *ResourceEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResourceEntry{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ResourceEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResourceEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResourceEntry) Path(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *ResourceEntry) PathLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ResourceEntry) Buffer(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ResourceEntry) BufferLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ResourceEntry) BufferBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ResourceEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ResourceEntryAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(path), 0)
}
func ResourceEntryStartPathVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func ResourceEntryAddBuffer(builder *flatbuffers.Builder, buffer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(buffer), 0)
}
func ResourceEntryStartBufferVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ResourceEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
