api: io.almagest.omniql.v1
rid: Application/io.almagest.omniql.*/Schema/Main/Enumeration/BasicTypes
spec:
  metadata:
    application: io.almagest.omniql.*
    kind: Enumeration
    name: ApplicationTypes
  kind: UnsignedShort
  items:
  - name: Enumeration
  - name: Resource
  - name: Table
  - name: Union
  - name: EnumerationGroup
  - name: EnumerationItem
  - name: UnionResource
  - name: UnionTable
  - name: Documentation
  - name: Field
  - name: Metadata
  groups:
  - name: Resource
    items:
    - Table
    - Union
    - Resource
    - Enumeration